name: Node CI/CD

on:
  # push:
  # branches:
  #   - main
  # paths:
  #   - "docker/app1-hello/node"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [service-a, service-b]
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "25"

      - name: Install dependencies
        working-directory: docker/app1-hello/node
        run: npm ci

      - name: Run tests
        working-directory: docker/app1-hello/node
        run: npm test --if-present
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    strategy:
      matrix:
        service:
          - {
              name: "service-a",
              docker_name: "tax-service-a",
              path: "docker/app2-tax-calculator/node/service-a",
            }
          - {
              name: "service-b",
              docker_name: "tax-service-b",
              path: "docker/app2-tax-calculator/node/service-b",
            }

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.service.path }}
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/hello-node:latest"
  deploy-aws-eks:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          aws-region: ap-southeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name cicd-cluster --region ap-southeast-2

      - name: Verify connection
        run: kubectl verify nodes

      - name: Deploy to AWS EKS
        run: |
          kubectl apply -f k8s/aws/app2-tax-calculator/service-a
          kubectl apply -f k8s/aws/app2-tax-calculator/service-b
